### ISSUE TITLE
Surface Brightness calculation in ugali.analysis.results.py should use azimuthally-averaged half-light radius 

### ISSUE THREAD

**Issue by willcerny** [DarkEnergySurvey/ugali#78]
https://github.com/DarkEnergySurvey/ugali/blob/00b30c5ac84e4cada338fb77d33aa31afabca7bb/ugali/analysis/results.py#L267

Arguably, this line should be using the variable `rsize` (the azimuthally averaged half-light radius in arcmin) for the calculation (instead of `size`), since the SB formula is assuming a circular area.

**Comment by kadrlica** [comment]
Thanks @willcerny, I agree with this change. We dug into this some with the DES LSBG analysis, and determined that the azimuthally averaged formulation agrees with the (not quite unanimous...) convention in the community. For example, Section 2.2 of [Graham & Driver (2005)](https://arxiv.org/pdf/astro-ph/0503176.pdf) defines the surface brightness for a Sersic profile in terms of R_e, which is the geometric mean effective radius (see their Footnote 3).

Since this change will likely lead to an update in all ugali-derived surface brightnesses returned in the results yaml file, I want to call it to the attention of @sidneymau @mcnanna and @bechtol.

@willcerny could you create a pull request with this change?

**Comment by kadrlica** [comment]
@willcerny also note that `size` and `rsize` are **physical** quantities measured in kpc not arcmin:
https://github.com/DarkEnergySurvey/ugali/blob/00b30c5ac84e4cada338fb77d33aa31afabca7bb/ugali/analysis/results.py#L203-L215

**Comment by willcerny** [comment]
Sure, I can do the pull request. Do we also want to switch to using Mv_martin rather than M_v?

**Comment by kadrlica** [comment]
Mv_martin is not always calculated, so probably need a switch to use M_v if it is not available.
